pipeline{
    agent any
    stages {
        stage('Build'){
            steps{
                bat 'docker run -p 8081:80 --network MyMicroserviceAppNetwork --rm --name recipes recipecatalogue'
            }
        }
    }
}